name: Bug Report
description: File a bug report
title: "<TITLE HERE>"
labels: ["bug"]
body:
- type: checkboxes
  attributes:
    label: Consent
    options:
    - label: I verified that there is no open/closed issue for the same subject.
      required: true
    - label: I understand that **YTMDesktop have NO affiliation with Google or YouTube**
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: input
  attributes:
    label: YTMDesktop
    description: "YTMDesktop version"
    placeholder: v1.2.3
  validations:
    required: true
- type: input
  attributes:
    label: OS
    description: "Which OS are you using?"
    value: Windows
  validations:
    required: true
- type: input
  attributes:
    label: OS Version
    description: "Which OS Version are you on?"
    value: "10"
  validations:
    required: true
- type: dropdown
  attributes:
    label: Arch
    description: "Which arch are you using?"
    options:
      - x64
      - x86
      - ARM64
  validations:
    required: true
- type: input
  attributes:
    label: Installation way
    description: "like .exe or snapcraft or another way"
    placeholder: .exe
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? Screenshots? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
