name: Feature request
description: Suggest an idea for this project
title: "<title>"
body:
- type: checkboxes
  attributes:
    label: Consent
    options:
    - label: I verified that there is no open issue for the same subject.
      required: true
    - label: I understand that **YTMDesktop have NO affiliation with Google or YouTube**
      required: true
- type: textarea
  attributes:
    label: Feature
    description: Describe the feature you'd like
  validations:
    required: true
- type: textarea
  attributes:
    label: Solution
    description: Describe the solution you'd like
  validations:
    required: false
- type: textarea
  attributes:
    label: Alternatives
    description: Describe alternatives you've considered
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? Screenshots? References? Anything that will give us more context about the feature you are wish to add!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
