---
name: Application Build

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            { name: "linux", image: "ubuntu-24.04", arch: "x64" },
            { name: "linux", image: "ubuntu-24.04-arm", arch: "arm64" },
            { name: "windows", image: "windows-2025", arch: "x64" },
            { name: "windows", image: "windows-11-arm", arch: "arm64" },
            { name: "macos", image: "macos-26-intel", arch: "x64" },
            { name: "macos", image: "macos-26", arch: "arm64" },
          ]
      fail-fast: false

    runs-on: ${{ matrix.os.image }}

    steps:
      - name: Github checkout
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/setup@v3
        with:
          runtime: node@lts
          cache: true

      - name: Install libdbus
        if: matrix.os.name == 'linux'
        run: sudo apt-get install libdbus-1-dev pkg-config -y

      - name: Make (${{ matrix.os.arch }})
        env:
          YTMD_UPDATE_FEED_OWNER: ${{ vars.YTMD_UPDATE_FEED_OWNER }}
          YTMD_UPDATE_FEED_REPOSITORY: ${{ vars.YTMD_UPDATE_FEED_REPOSITORY }}
        run: pnpm make --arch ${{ matrix.os.arch }}

      - name: Upload artifacts (${{ matrix.os.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os.name }}-${{ matrix.os.arch }}
          path: |
            out/make/squirrel.windows/${{ matrix.os.arch }}/*.exe
            out/make/deb/${{ matrix.os.arch }}/*.deb
            out/make/rpm/${{ matrix.os.arch }}/*.rpm
            out/make/zip/darwin/${{ matrix.os.arch }}/*.zip
