---
name: Application Publish

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        arch: ["x64", "arm64"]
        exclude:
          # Mitigation for Electron Forge naming conflict. See #1183.
          - os: "windows-latest"
            arch: "arm64"

      fail-fast: true # Explicitly failing fast because this is a publish. We want to bail the entire release if something went wrong with another build

    runs-on: ${{ matrix.os }}

    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/setup@v3.0.0
        with:
          runtime: node@lts
          cache: true

      - name: Make (${{ matrix.arch }})
        env:
          YTMD_UPDATE_FEED_OWNER: ${{ vars.YTMD_UPDATE_FEED_OWNER }}
          YTMD_UPDATE_FEED_REPOSITORY: ${{ vars.YTMD_UPDATE_FEED_REPOSITORY }}
        run: pnpm make --arch ${{ matrix.arch }}

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-path: out/make/**/*

      - name: Release From Make (${{ matrix.arch }})
        run: pnpm release:frommake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YTMD_UPDATE_FEED_OWNER: ${{ vars.YTMD_UPDATE_FEED_OWNER }}
          YTMD_UPDATE_FEED_REPOSITORY: ${{ vars.YTMD_UPDATE_FEED_REPOSITORY }}
